apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-demo
  template:
    metadata:
      labels:
        app: storage-demo
    spec:
      containers:
        - name: storage-demo
          image: ghcr.io/nathansegers/kubernetes-storage-test
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage-data
              mountPath: /data
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: pvc-database