apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-database
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # for K3d
  hostPath:
      # Make sure these paths are shared in the File Sharing options of Docker Desktop when you're working on Mac or Linux
    path: "/tmp" # Windows, make sure this directory exists. This path is the equivalent in Windows for "C:/tmp". But because of the extra layer of WSL, Docker (and thus Kubernetes in this case), cannot access our Windows files otherwise.